export const CRAFTS = {
  admin_stick: {
    name: "admin_stick",
    title: "ADMIN STICK",
    titleFormat: "colorC formatL",
    image: "/img/recipes/admin_stick.png",
    description: "Un palo para dominarlos a todos!",
    descriptionFormat: "colorD formatR",
    tag: "minecraft:stick",
  },
  bolsita: {
    name: "bolsita",
    title: "Bolsita",
    titleFormat: "colorE formatR",
    image: "/img/recipes/bolsita.png",
    subimage: "/img/recipes/two_slots_bundle.png",
    description: ["0/64", "Mete tus items aquí"],
    descriptionFormat: "color7 formatR",
    tag: "minecraft:bundle",
  },
  campfire_rotten_flesh: {
    name: "campfire_rotten_flesh",
    title: "Filete crudo",
    titleFormat: "colorF formatR",
    image: "/img/recipes/rotten_flesh.png",
    description: "Comida y bebida",
    descriptionFormat: "color9 formatR",
    tag: "minecraft:beef",
    paired_item: {
      name: "Hueso",
      description: "Ingredientes",
      tag: "minecraft:bone",
      chance: "50%",
    },
  },
  scissors: {
    name: "scissors",
    title: "Tijeras",
    titleFormat: "colorE formatL",
    image: "/img/recipes/scissors.png",
    description: "Vacas, cerdos, zombies",
    descriptionFormat: "color7 formatR",
    tag: "minecraft:shears",
  },
  spawner_breaker: {
    name: "spawner_breaker",
    title: "Rompe-Spawners",
    titleFormat: "color6 formatL",
    image: "/img/recipes/spawner_breaker.png",
    description: "50% de romper el spawner o romperse",
    descriptionFormat: "colorD formatR",
    tag: "minecraft:golden_pickaxe",
  },
  zombification_potion: {
    name: "zombification_potion",
    title: "Poción de Zombificación",
    titleFormat: "colorZombPot formatL",
    image: "/img/recipes/zombification_potion.png",
    description: "Convierte a un aldeano en zombie",
    descriptionFormat: "colorB formatR",
    tag: "minecraft:splash_potion",
  },
};
